# app_streamlit.py
# Run: streamlit run app_streamlit.py
# Make sure you have outputs/predictions_latest_month.csv generated by your pipeline.

import os
from datetime import datetime, timedelta, timezone

import pandas as pd
import requests
import streamlit as st
import plotly.graph_objects as go

PRED_DEFAULT = "outputs/predictions_latest_month.csv"

st.set_page_config(page_title="Earthquake Risk Predictor", layout="wide")

st.title("🌍 Earthquake Risk Predictor + Live Monitoring (48h)")
st.caption("Predicted next-month risk by grid cell + live earthquakes from USGS (last 48 hours).")

# ----------------------------
# Helpers
# ----------------------------
@st.cache_data(ttl=300)
def load_predictions(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    # Support either YYYY-MM-DD or datetime
    df["month_date"] = pd.to_datetime(df["month_date"], errors="coerce")
    # Parse cell_id -> lat/lon (expects "lat_lon")
    latlon = df["cell_id"].astype(str).str.split("_", expand=True)
    df["lat"] = pd.to_numeric(latlon[0], errors="coerce")
    df["lon"] = pd.to_numeric(latlon[1], errors="coerce")
    df["risk_prob"] = pd.to_numeric(df["risk_prob"], errors="coerce").fillna(0.0)
    df["predicted_quake"] = pd.to_numeric(df["predicted_quake"], errors="coerce").fillna(0).astype(int)
    df["predicted_class"] = pd.to_numeric(df["predicted_class"], errors="coerce").fillna(-1).astype(int)
    df = df.dropna(subset=["lat", "lon"]).reset_index(drop=True)
    return df


@st.cache_data(ttl=300)
def fetch_live_quakes_usgs(min_magnitude: float = 4.0) -> pd.DataFrame:
    """
    USGS FDSN query for last 48 hours.
    """
    end = datetime.now(timezone.utc)
    start = end - timedelta(hours=48)

    url = "https://earthquake.usgs.gov/fdsnws/event/1/query"
    params = {
        "format": "geojson",
        "starttime": start.strftime("%Y-%m-%dT%H:%M:%S"),
        "endtime": end.strftime("%Y-%m-%dT%H:%M:%S"),
        "minmagnitude": float(min_magnitude),
        "orderby": "time",
    }

    r = requests.get(url, params=params, timeout=15)
    r.raise_for_status()
    data = r.json()

    rows = []
    for f in data.get("features", []):
        prop = f.get("properties", {}) or {}
        geom = f.get("geometry", {}) or {}
        coords = geom.get("coordinates", []) or []
        if len(coords) < 2:
            continue
        lon, lat = coords[0], coords[1]
        mag = prop.get("mag")
        t_ms = prop.get("time")

        t_str = ""
        if t_ms:
            t_str = datetime.fromtimestamp(t_ms / 1000, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        rows.append(
            {
                "lat": float(lat),
                "lon": float(lon),
                "mag": float(mag) if mag is not None else None,
                "time": t_str,
                "type": "Live Quake (USGS 48h)",
            }
        )

    return pd.DataFrame(rows)


def build_map(pred_df: pd.DataFrame, live_df: pd.DataFrame) -> go.Figure:
    class_names = {0: "6.0–6.9", 1: "7.0–7.9", 2: "8.0+"}

    fig = go.Figure()

    # 1) Prediction grid
    fig.add_trace(
        go.Scattermapbox(
            lat=pred_df["lat"],
            lon=pred_df["lon"],
            mode="markers",
            marker=go.scattermapbox.Marker(
                size=16,
                color=pred_df["risk_prob"],
                colorscale="Viridis",
                opacity=0.7,
                showscale=True,
                colorbar=dict(
                    title="Risk",
                    thickness=18,
                    x=0.92,
                    tickvals=[0, 0.5, 1],
                    ticktext=["Low", "Medium", "High"],
                ),
            ),
            text=pred_df.apply(
                lambda r: (
                    f"<b>Cell:</b> {r['cell_id']}"
                    f"<br><b>Risk:</b> {r['risk_prob']:.2f}"
                    f"<br><b>Predicted quake:</b> {int(r['predicted_quake'])}"
                    f"<br><b>Magnitude class:</b> {class_names.get(r['predicted_class'], 'N/A')}"
                ),
                axis=1,
            ),
            hoverinfo="text",
            name="Predicted Risk Zones",
        )
    )

    # 2) Alert zones: risk_prob >= threshold
    alerts = pred_df[pred_df["predicted_quake"] == 1].copy()
    if not alerts.empty:
        fig.add_trace(
            go.Scattermapbox(
                lat=alerts["lat"],
                lon=alerts["lon"],
                mode="markers+text",
                marker=go.scattermapbox.Marker(size=12, color="white"),
                text=alerts["predicted_class"].map(lambda x: f"⚠️ {class_names.get(int(x), 'High Risk')}"),
                textposition="top center",
                textfont=dict(size=12, color="white"),
                hoverinfo="none",
                name="Alert Zones (Predicted Quake)",
            )
        )

    # 3) Live quakes
    if live_df is not None and not live_df.empty:
        fig.add_trace(
            go.Scattermapbox(
                lat=live_df["lat"],
                lon=live_df["lon"],
                mode="markers",
                marker=go.scattermapbox.Marker(size=10, color="cyan", opacity=0.9),
                text=live_df.apply(
                    lambda r: f"<b>LIVE QUAKE</b><br>Mag: {r['mag']}<br>Time: {r['time']}",
                    axis=1,
                ),
                hoverinfo="text",
                name="Live Quakes (48h)",
            )
        )

    fig.update_layout(
        template="plotly_dark",
        mapbox_style="carto-darkmatter",
        mapbox=dict(center=dict(lat=20, lon=0), zoom=1.4),
        margin=dict(l=0, r=0, t=50, b=0),
        title=dict(text="Global Earthquake Risk & Live Monitoring", x=0.02, font=dict(size=22)),
        legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01, bgcolor="rgba(0,0,0,0.5)"),
    )
    return fig


# ----------------------------
# Sidebar controls
# ----------------------------
with st.sidebar:
    st.header("Controls")
    pred_path = st.text_input("Predictions CSV path", value=PRED_DEFAULT)
    min_mag_live = st.slider("Live quakes min magnitude", min_value=1.0, max_value=6.0, value=4.0, step=0.5)
    st.divider()
    st.write("Tip: Run the pipeline first to generate the CSV.")
    rerun = st.button("🔄 Refresh data")

if rerun:
    st.cache_data.clear()

# ----------------------------
# Load + render
# ----------------------------
if not os.path.exists(pred_path):
    st.error(f"Predictions file not found: {pred_path}")
    st.info("Run: python pipeline/08_predict_latest_month.py (or python pipeline/run_all.py)")
    st.stop()

pred_df = load_predictions(pred_path)

# Live data (safe handling)
try:
    live_df = fetch_live_quakes_usgs(min_magnitude=min_mag_live)
except Exception as e:
    st.warning(f"Could not fetch live quakes from USGS: {e}")
    # Fallback points (so UI still shows something)
    live_df = pd.DataFrame(
        [
            {"lat": 35.6895, "lon": 139.6917, "mag": 4.5, "time": "Fallback", "type": "Live Quake"},
            {"lat": -12.0464, "lon": -77.0428, "mag": 5.2, "time": "Fallback", "type": "Live Quake"},
        ]
    )

# Summary metrics
c1, c2, c3, c4 = st.columns(4)
latest_month = pred_df["month_date"].max() if pred_df["month_date"].notna().any() else None
latest_month_str = latest_month.strftime("%Y-%m-%d") if latest_month is not None and pd.notna(latest_month) else "N/A"
c1.metric("Latest month", latest_month_str)
c2.metric("Grid cells", len(pred_df))
c3.metric("Alert cells", int((pred_df["predicted_quake"] == 1).sum()))
c4.metric("Live quakes (48h)", 0 if live_df is None else len(live_df))

# Map
fig = build_map(pred_df, live_df)
st.plotly_chart(fig, use_container_width=True)

# Alerts list
st.subheader("🚨 Active Alerts")
alerts = pred_df[pred_df["predicted_quake"] == 1].copy().sort_values("risk_prob", ascending=False)

if alerts.empty:
    st.write("No high-risk zones detected at this threshold.")
else:
    class_names = {0: "6.0–6.9", 1: "7.0–7.9", 2: "8.0+"}
    alerts_display = alerts[["cell_id", "risk_prob", "predicted_class"]].copy()
    alerts_display["predicted_class"] = alerts_display["predicted_class"].map(lambda x: class_names.get(int(x), "N/A"))
    st.dataframe(alerts_display, use_container_width=True)

# Raw data expandable
with st.expander("See raw predictions"):
    st.dataframe(pred_df[["cell_id", "month_date", "risk_prob", "predicted_class"]].sort_values("risk_prob", ascending=False),
                 use_container_width=True)